site_name: Red Panda Studies
repo_url: https://github.com/jbcodeforce/redpanda-studies
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Use cases: usecases.md
  - Kubernetes: k8s.md
  - Back to: https://jbcodeforce.github.io/

theme: 
  name: material
  palette:
    scheme: default
    primary: deep orange
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.instant
      - navigation.indexes
      - navigation.tracking
      - navigation.tabs.sticky
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - pymdownx.highlight
  - meta
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
